# Week 5 handin

# Assignment

## Exercise 1
1. Go to https://www.dst.dk/da/Statistik/brug-statistikken/muligheder-i-statistikbanken/api#testkonsol
2. Open 'Konsol' and click 'Start Konsol'
3. In the console at pt 1: choose 'Retrieve tables', pt 2: choose get request and json format and pt 3: execute:
  1. check the result
  2. in the code below this same get request is used to get information about all available data tables in 'databanken'. 
4. Change pt. 1 in the console to 'Retrieve data', pt 2: 'get request' and Table id: 'FOLK1A', format: csv, delimiter: semicolon and click: 'Variable and value codes' and choose some sub categories (Hint: hover over the codes to see their meaning). Finally execute and see what data you get.
5. With data aggregation and data visualization answer the following questions:
  1. What is the change in pct of divorced danes from 2008 to 2020?
  2. Which of the 5 biggest cities has the highest percentage of 'Never Married' in 2020?
  3. Show a bar chart of changes in marrital status in Copenhagen from 2008 till now
  4. Show 2 plots in same figure: 'Married' and 'Never Married' for all ages in DK in 2020 (Hint: x axis is age from 0-125, y axis is how many people in the 2 categories). Add lengend to show names on graphs
  
## Ex2 Use another table (extra)
Choose any of the other tables in 'databanken' to find interesting data.
1. Collect the data
2. Pose 5 or more interesing questions to the data
3. Answer the questions by aggregating the data
4. Illustrate the answers with visual plots

In [44]:
import pandas as pd 
url = 'https://api.statbank.dk/v1/tables'
dst = pd.read_json(url)
dst.to_csv('dk-stat-all-tables.csv', encoding='utf-8', index=False)
dst[:20]

,id,text,unit,updated,firstPeriod,latestPeriod,active,variables
0,FOLK1A,Folketal den 1. i kvartalet,antal,2021-02-11T08:00:00,2008K1,2021K1,True,"[område, køn, alder, civilstand, tid]"
1,FOLK1B,Folketal den 1. i kvartalet,antal,2021-02-11T08:00:00,2008K1,2021K1,True,"[område, køn, alder, statsborgerskab, tid]"
2,FOLK1C,Folketal den 1. i kvartalet,antal,2021-02-11T08:00:00,2008K1,2021K1,True,"[område, køn, alder, herkomst, oprindelsesland..."
3,FOLK1D,Folketal den 1. i kvartalet,antal,2021-02-11T08:00:00,2008K1,2021K1,True,"[område, køn, alder, statsborgerskab, tid]"
4,FOLK1E,Folketal den 1. i kvartalet,antal,2021-02-11T08:00:00,2008K1,2021K1,True,"[område, køn, alder, herkomst, tid]"
5,FOLK2,Folketal 1. januar,antal,2021-02-11T08:00:00,1980,2021,True,"[alder, køn, herkomst, statsborgerskab, oprind..."
6,KRYDS1,Folketal 1. januar,antal,2021-02-11T08:00:00,2019,2021,True,"[Hovedpersons herkomst, Hovedpersons fødeland,..."
7,KRYDS2,Personer med dansk oprindelse 1. januar,antal,2021-02-11T08:00:00,2019,2021,True,"[Hovedpersons fødeland, forældres fødeland og ..."
8,KRYDS3,Folketal 1. januar,antal,2021-02-11T08:00:00,2019,2021,True,"[Hovedpersons herkomst, Hovedpersons fødeland,..."
9,KRYDS4,Folketal 1. januar,antal,2021-02-11T08:00:00,2019,2021,True,"[Hovedpersons herkomst, forældres fødeland og ..."
10,FOLK3,Folketal 1. januar,antal,2021-02-11T08:00:00,2008,2021,True,"[fødselsdag, fødselsmåned, fødselsår, tid]"
11,FT,Folketal (summariske tal fra folketællinger),antal,2021-02-11T08:00:00,1769,2021,True,"[hovedlandsdele, tid]"
12,BEF5F,Personer født på Færøerne og bosat i Danmark 1...,antal,2021-02-11T08:00:00,2008,2021,True,"[køn, alder, forældrenes fødested, tid]"
13,BEF5G,Personer født i Grønland og bosat i Danmark 1....,antal,2021-02-11T08:00:00,2008,2021,True,"[køn, alder, forældrenes fødested, tid]"
14,BEF5,Folketal pr. 1. januar,antal,2021-02-11T08:00:00,1990,2021,True,"[køn, alder, fødeland, tid]"
15,BY3,Folketal 1. januar,-,2020-06-11T08:00:00,2017,2020,True,"[byområder og landdistrikter, folketal, areal ..."
16,BY1,Folketal 1. januar,antal,2020-04-29T08:00:00,2010,2020,True,"[byområder og landdistrikter, alder, køn, tid]"
17,BY4,Husstande 1. januar,antal,2020-04-29T08:00:00,2010,2020,True,"[byområder og landdistrikter, husstandstype, a..."
18,BY2,Folketal 1. januar,antal,2020-04-29T08:00:00,2010,2020,True,"[kommune, bystørrelse, alder, køn, tid]"
19,BEF4,Folketal 1. januar,antal,2020-04-01T08:00:00,1901,2020,True,"[øer, tid]"

# Status

Finished all mandatory tasks

Uncomment the function at the button to run the solution for the subtask

## Exercise 1
#### Task 1 - 4 is anwsered by using the provided console

In [223]:
import matplotlib.pyplot as plt

def get_data_frame(url):
    return pd.read_csv(url, delimiter = ";")

# Task 5 A
# What is the change in pct of divorced danes from 2008 to 2020?
def task_5_a() :
    print("Task 5 A")

    url = "https://api.statbank.dk/v1/data/FOLK1A/CSV?delimiter=Semicolon&CIVILSTAND=F&Tid=2008K1%2C2020K4"
    df = get_data_frame(url)

    d_2008 = df.iloc[0,2]
    d_2020 = df.iloc[1,2]
    diff_in_pct = round(d_2020 / d_2008 * 100, 2)

    print("2008: {d_2008}\n2020: {d_2020}\nDiff: {diff}%".format(d_2008 = d_2008, d_2020 = d_2020, diff = diff_in_pct))

# Task 5 B
# Which of the 5 biggest cities has the highest percentage of 'Never Married' in 2020?
def task_5_b():
    print("Task 5 B")

    url = "https://api.statbank.dk/v1/data/FOLK1A/CSV?delimiter=Semicolon&Tid=2020K4&OMR%C3%85DE=101%2C461%2C630%2C751%2C851&CIVILSTAND=TOT%2CU"
    df = get_data_frame(url)
    df = df.sort_values(by = "OMRÅDE")

    areas = []

    for index in range(0, len(df.index), 2):
        area_name = df.iloc[index, 1]
        area_population = df.iloc[index, 3]
        area_unmarried = df.iloc[index + 1, 3]
        area_unmarried_pct = round(area_unmarried / area_population * 100, 2)

        area = {"area": area_name, "population": area_population, "unmarried": area_unmarried, "pct": area_unmarried_pct}
        areas.append(area)

    areas = sorted(areas, key = lambda x: x["pct"], reverse = True)
    print(areas[0])

# Task 5 C
# Show a bar chart of changes in marrital status in Copenhagen from 2008 till now
def task_5_c():
    print("Task 5 C")

    url = "https://api.statbank.dk/v1/data/FOLK1A/CSV?timeOrder=Ascending&delimiter=Semicolon&OMR%C3%85DE=101&CIVILSTAND=G&Tid=*"
    df = get_data_frame(url)

    timeline = {}

    for index in range(0, len(df.index)):
        timeline[df.iloc[index, 2]] = df.iloc[index, 3]

    plt.bar(timeline.keys(), timeline.values(), width = 0.5, align = "edge")
    plt.xticks(rotation = 75)
    plt.xlabel("Tid", fontsize = 10)
    plt.ylabel("Antal gifte", fontsize = 10)

# Task 5 D
# Show 2 plots in same figure: 'Married' and 'Never Married' for all ages in DK in 2020
# (Hint: x axis is age from 0-125, y axis is how many people in the 2 categories).
# Add lengend to show names on graphs
def task_5_d():
    print("Task 5 D")

    url = "https://api.statbank.dk/v1/data/FOLK1A/CSV?timeOrder=Ascending&delimiter=Semicolon&CIVILSTAND=U%2CG&ALDER=*&Tid=2020K4"
    df = get_data_frame(url)

    max_age = 125
    no_married_per_age = {}
    no_never_married_per_age = {}
    
    for index in range(1, max_age + 2):
        age = index - 1
        never_married = df.iloc[index, 3]
        married = df.iloc[index + max_age + 2, 3]
        
        no_married_per_age[age] = married
        no_never_married_per_age[age] = never_married
    
    ages = list(no_married_per_age.keys())
    married_per_age = list(no_married_per_age.values())
    never_married_per_age = list(no_never_married_per_age.values())
    
    plt.xlabel("Alder", fontsize = 10)
    plt.ylabel("Antal", fontsize = 10)
    plt.tick_params(axis = 'both', which = 'major', labelsize = 10)
    
    plt_married = plt.bar(ages, married_per_age, width = 0.5, linewidth = 0, align = "center", color = "red")
    plt_never_married = plt.bar(ages, never_married_per_age, width = 0.5, linewidth = 0, align = "center", color = "blue")
    
    plt.legend([plt_married, plt_never_married], ["Gift", "Aldrig gift"], loc = 1)
    
    
# task_5_a()
# task_5_b()
# task_5_c()
# task_5_d()